
import type { VocabularyItem } from './types';

export const MAX_QUESTIONS = 10;

// 小学5〜6年生向け英単語リスト (Comprehensive List for Grades 5-6)
export const VOCABULARY: VocabularyItem[] = [
    // --- Nouns (名詞) ---
    // School & Subjects
    { english: "subject", japanese: "科目", emoji: "📖" },
    { english: "English", japanese: "英語", emoji: "🗽🗣" },
    { english: "math", japanese: "算数", emoji: "🧮" },
    { english: "science", japanese: "理科", emoji: "🔬" },
    { english: "music", japanese: "音楽", emoji: "🎵" },
    { english: "art", japanese: "美術", emoji: "🎨" },
    { english: "history", japanese: "歴史", emoji: "📜" },
    { english: "P.E.", japanese: "体育", emoji: "🤸" },
    { english: "classroom", japanese: "教室", emoji: "🏫👭👬📝" },
    { english: "homework", japanese: "宿題", emoji: "✍️" },
    { english: "test", japanese: "テスト", emoji: "📝" },
    { english: "student", japanese: "生徒", emoji: "🧑‍🎓" },
    { english: "teacher", japanese: "先生", emoji: "👩‍🏫" },
    
    // Time & Seasons
    { english: "time", japanese: "時間", emoji: "⏰" },
    { english: "year", japanese: "年", emoji: "🗓️" },
    { english: "season", japanese: "季節", emoji: "🍂" },
    { english: "spring", japanese: "春", emoji: "🌸" },
    { english: "summer", japanese: "夏", emoji: "🌻" },
    { english: "fall", japanese: "秋", emoji: "🍁" },
    { english: "winter", japanese: "冬", emoji: "❄️" },
    { english: "month", japanese: "月", emoji: "📅" },
    { english: "January", japanese: "1月", emoji: "1️⃣🗓" },
    { english: "February", japanese: "2月", emoji: "2️⃣🗓" },
      { english: "March", japanese: "3月", emoji: "3️⃣🗓" },
      { english: "April", japanese: "4月", emoji: "4️⃣🗓" },
      { english: "may", japanese: "5月", emoji: "5️⃣🗓" },
      { english: "June", japanese: "6月", emoji: "6️⃣🗓" },
      { english: "July", japanese: "7月", emoji: "7️⃣🗓" },
      { english: "August", japanese: "8月", emoji: "8️⃣🗓" },
      { english: "September", japanese: "9月", emoji: "9️⃣🗓" },
      { english: "October", japanese: "10月", emoji: "🔟🗓" },
    { english: "November", japanese: "11月", emoji: "1️⃣1️⃣🗓" },
      { english: "December", japanese: "12月", emoji: "1️⃣2️⃣🗓" },
      { english: "week", japanese: "週", emoji: "📆" },
    { english: "day", japanese: "日", emoji: "☀️" },
    { english: "today", japanese: "今日", emoji: "📍" },
    { english: "yesterday", japanese: "昨日", emoji: "⏪" },
    { english: "tomorrow", japanese: "明日", emoji: "⏩" },
    { english: "morning", japanese: "朝", emoji: "🌅" },
    { english: "afternoon", japanese: "午後", emoji: "🏙️" },
    { english: "evening", japanese: "夕方", emoji: "🌆" },
    { english: "night", japanese: "夜", emoji: "🌃" },
    { english: "birthday", japanese: "誕生日", emoji: "🎂" },
    { english: "holiday", japanese: "休日", emoji: "🎉" },
    { english: "vacation", japanese: "休暇", emoji: "🏖️" },
    { english: "weekend", japanese: "週末", emoji: "🥳" },
    
    // People & Family
    { english: "friend", japanese: "友達", emoji: "🧑‍🤝‍🧑" },
    { english: "family", japanese: "家族", emoji: "👨‍👩‍👧‍👦" },
    { english: "mother", japanese: "母", emoji: "👩" },
    { english: "father", japanese: "父", emoji: "👨" },
    { english: "sister", japanese: "姉妹", emoji: "👧👧" },
    { english: "brother", japanese: "兄弟", emoji: "👦👦" },
    
    // Places & World
    { english: "place", japanese: "場所", emoji: "📍" },
    { english: "country", japanese: "国", emoji: "🗾" },
    { english: "world", japanese: "世界", emoji: "🌍" },
    { english: "Japan", japanese: "日本", emoji: "🇯🇵" },
    { english: "America", japanese: "アメリカ", emoji: "🇺🇸" },
    { english: "Canada", japanese: "カナダ", emoji: "🇨🇦" },
    { english: "China", japanese: "中国", emoji: "🇨🇳" },
    { english: "Australia", japanese: "オーストラリア", emoji: "🇦🇺" },
    { english: "United Kingdom", japanese: "イギリス", emoji: "🇬🇧" },
    { english: "town", japanese: "町", emoji: "🏘️" },
    { english: "city", japanese: "市", emoji: "🏙️" },
    { english: "station", japanese: "駅", emoji: "🚉" },
    { english: "airport", japanese: "空港", emoji: "🛩️" },
    { english: "library", japanese: "図書館", emoji: "🏛️" },
    { english: "museum", japanese: "博物館", emoji: "🖼️" },
    { english: "hospital", japanese: "病院", emoji: "🏥" },
    { english: "post office", japanese: "郵便局", emoji: "🏤" },
    { english: "park", japanese: "公園", emoji: "🌳" },
    { english: "store", japanese: "店", emoji: "🏪" },
    { english: "restaurant", japanese: "レストラン", emoji: "🍴" },
    
    // Food & Drink
    { english: "food", japanese: "食べ物", emoji: "🍔" },
    { english: "breakfast", japanese: "朝食", emoji: "🥞" },
    { english: "lunch", japanese: "昼食", emoji: "🍱" },
    { english: "dinner", japanese: "夕食", emoji: "🍝" },
    { english: "fruit", japanese: "果物", emoji: "🍓" },
    { english: "vegetable", japanese: "野菜", emoji: "🥦" },
    { english: "rice", japanese: "ごはん", emoji: "🍚" },
    { english: "bread", japanese: "パン", emoji: "🍞" },
    { english: "water", japanese: "水", emoji: "💧" },
    { english: "juice", japanese: "ジュース", emoji: "🧃" },
    
    // Hobbies & Sports
    { english: "hobby", japanese: "趣味", emoji: "🏸" },
    { english: "sport", japanese: "スポーツ", emoji: "⚽" },
    { english: "game", japanese: "ゲーム", emoji: "🎮" },
    { english: "movie", japanese: "映画", emoji: "🎬" },
    { english: "music", japanese: "音楽", emoji: "🎵" },
    { english: "song", japanese: "歌", emoji: "🎤" },
    { english: "picture", japanese: "絵、写真", emoji: "🖼️" },
    { english: "book", japanese: "本", emoji: "📚" },
    { english: "instrument", japanese: "楽器", emoji: "🎺" },

    // Abstract
    { english: "future", japanese: "未来", emoji: "🚀" },
    { english: "dream", japanese: "夢", emoji: "🌠" },
    { english: "language", japanese: "言語", emoji: "🗣️" },
    { english: "story", japanese: "物語", emoji: "📖" },
    { english: "letter", japanese: "手紙", emoji: "✉️" },
    { english: "number", japanese: "数字", emoji: "🔢" },

    // --- Verbs (動詞) ---
    // Regular Verbs
    { english: "be (am, is, are)", japanese: "です、いる", emoji: "🙌" },
    { english: "play", japanese: "遊ぶ、演奏する", emoji: "⏯️" },
    { english: "like", japanese: "好き", emoji: "❤️" },
    { english: "have", japanese: "持っている", emoji: "🤝" },
    { english: "live", japanese: "住んでいる", emoji: "🏠" },
    { english: "listen", japanese: "聞く", emoji: "👂" },
    { english: "look", japanese: "見る", emoji: "👀" },
    { english: "watch", japanese: "見る", emoji: "📺" },
    { english: "walk", japanese: "歩く", emoji: "🚶" },
    { english: "talk", japanese: "話す", emoji: "💬" },
    { english: "speak", japanese: "話す", emoji: "🗣️" },
    { english: "study", japanese: "勉強する", emoji: "📚" },
    { english: "start", japanese: "始める", emoji: "🏁" },
    { english: "finish", japanese: "終える", emoji: "✅" },
    { english: "help", japanese: "助ける", emoji: "🆘" },
    { english: "want", japanese: "欲しい", emoji: "🙏" },
    { english: "visit", japanese: "訪れる", emoji: "🧳" },
    { english: "enjoy", japanese: "楽しむ", emoji: "🎉" },
    { english: "practice", japanese: "練習する", emoji: "💪" },
    { english: "use", japanese: "使う", emoji: "🔧" },
    { english: "cook", japanese: "料理する", emoji: "🍳" },
    { english: "clean", japanese: "掃除する", emoji: "🧹" },
    { english: "need", japanese: "必要とする", emoji: "❗" },

    // Irregular Verbs (Present)
    { english: "go", japanese: "行く", emoji: "➡️" },
    { english: "come", japanese: "来る", emoji: "⬅️" },
    { english: "do", japanese: "する", emoji: "👍" },
    { english: "get", japanese: "得る", emoji: "🙌" },
    { english: "make", japanese: "作る", emoji: "🛠️" },
    { english: "see", japanese: "見る、会う", emoji: "👁️" },
    { english: "eat", japanese: "食べる", emoji: "🍴" },
    { english: "drink", japanese: "飲む", emoji: "🥤" },
    { english: "read", japanese: "読む", emoji: "📖" },
    { english: "write", japanese: "書く", emoji: "✍️" },
    { english: "run", japanese: "走る", emoji: "🏃" },
    { english: "swim", japanese: "泳ぐ", emoji: "🏊" },
    { english: "sing", japanese: "歌う", emoji: "🎤" },
    { english: "sleep", japanese: "寝る", emoji: "😴" },
    { english: "know", japanese: "知っている", emoji: "💡" },
    { english: "think", japanese: "考える", emoji: "🧠" },
    { english: "take", japanese: "取る、持って行く", emoji: "🚶‍♂️" },
    { english: "buy", japanese: "買う", emoji: "🛒" },
    { english: "wear", japanese: "着る", emoji: "👕" },
    { english: "teach", japanese: "教える", emoji: "👩‍🏫" },
    { english: "fly", japanese: "飛ぶ", emoji: "✈️" },

    // Past Tense Verbs (過去形)
    { english: "was / were", japanese: "だった (beの過去)", emoji: "⏪🔙" },
    { english: "went", japanese: "行った (goの過去)", emoji: "➡️🔙" },
      { english: "came", japanese: "来た (comeの過去)", emoji: "⬅️🔙" },
    { english: "had", japanese: "持っていた (haveの過去)", emoji: "🤝🔙" },
    { english: "did", japanese: "した (doの過去)", emoji: "👍🔙" },
    { english: "got", japanese: "得た (getの過去)", emoji: "🙌🔙" },
    { english: "made", japanese: "作った (makeの過去)", emoji: "🛠️🔙" },
    { english: "saw", japanese: "見た (seeの過去)", emoji: "👁️🔙" },
    { english: "ate", japanese: "食べた (eatの過去)", emoji: "🍴🔙" },
    { english: "drank", japanese: "飲んだ (drinkの過去)", emoji: "🥤🔙" },
    { english: "read (red)", japanese: "読んだ (readの過去)", emoji: "🗣📖🔙" },
    { english: "wrote", japanese: "書いた (writeの過去)", emoji: "✍️🔙" },
      { english: "ran", japanese: "走った (runの過去)", emoji: "🏃🔙" },
    { english: "swam", japanese: "泳いだ (swimの過去)", emoji: "🏊🔙" },
    { english: "sang", japanese: "歌った (singの過去)", emoji: "🎤🔙" },
    { english: "slept", japanese: "寝た (sleepの過去)", emoji: "😴🔙" },
    { english: "knew", japanese: "知っていた (knowの過去)", emoji: "💡🔙" },
    { english: "thought", japanese: "考えた (thinkの過去)", emoji: "🧠🔙" },
    { english: "took", japanese: "取った (takeの過去)", emoji: "🚶‍♂️🤲🔙" },
    { english: "bought", japanese: "買った (buyの過去)", emoji: "🛒🔙" },
    { english: "wore", japanese: "着た (wearの過去)", emoji: "👕🔙" },
    { english: "taught", japanese: "教えた (teachの過去)", emoji: "👩‍🏫🔙" },
    { english: "flew", japanese: "飛んだ (flyの過去)", emoji: "✈️🔙" },
      { english: "studied", japanese: "勉強した (studyの過去)", emoji: "📚🔙" },
    { english: "played", japanese: "遊んだ (playの過去)", emoji: "⏯️🔙" },
    { english: "liked", japanese: "好きだった (likeの過去)", emoji: "❤️🔙" },

    // --- Adjectives (形容詞) ---
      { english: "good", japanese: "良い", emoji: "👍" },
    { english: "bad", japanese: "悪い", emoji: "👎" },
    { english: "big", japanese: "大きい", emoji: "🐘" },
    { english: "small", japanese: "小さい", emoji: "🐁" },
    { english: "hot", japanese: "暑い", emoji: "🔥" },
    { english: "cold", japanese: "寒い", emoji: "❄️" },
    { english: "new", japanese: "新しい", emoji: "✨" },
    { english: "old", japanese: "古い", emoji: "🏛️" },
    { english: "happy", japanese: "嬉しい", emoji: "😊" },
    { english: "sad", japanese: "悲しい", emoji: "😢" },
    { english: "delicious", japanese: "おいしい", emoji: "😋" },
    { english: "beautiful", japanese: "美しい", emoji: "💖" },
    { english: "favorite", japanese: "お気に入りの", emoji: "⭐" },
    { english: "famous", japanese: "有名な", emoji: "🌟" },
    { english: "interesting", japanese: "面白い", emoji: "😮" },
    { english: "exciting", japanese: "わくわくする", emoji: "🎢" },
    { english: "difficult", japanese: "難しい", emoji: "😥" },
    { english: "easy", japanese: "簡単な", emoji: "😎" },
    { english: "busy", japanese: "忙しい", emoji: "🏃‍♀️" },
    { english: "tired", japanese: "疲れた", emoji: "😪" },
    { english: "hungry", japanese: "お腹がすいた", emoji: "🍔" },
    { english: "full", japanese: "お腹がいっぱい", emoji: "🤰" },
    { english: "kind", japanese: "親切な", emoji: "🤗" },
    { english: "great", japanese: "すごい、素晴らしい", emoji: "🎉" },
    { english: "wonderful", japanese: "素晴らしい", emoji: "🤩" },

    // --- Adverbs (副詞) ---
    { english: "always", japanese: "いつも", emoji: "🔄" },
    { english: "usually", japanese: "たいてい", emoji: "👍" },
    { english: "often", japanese: "よく", emoji: "😄" },
    { english: "sometimes", japanese: "時々", emoji: "🤔" },
    { english: "never", japanese: "決して〜ない", emoji: "🚫" },
    { english: "well", japanese: "上手に", emoji: "👌" },
    { english: "fast", japanese: "速く", emoji: "💨" },
    { english: "early", japanese: "早く", emoji: "🌅" },
    { english: "late", japanese: "遅く", emoji: "🌃" },
    { english: "very", japanese: "とても", emoji: "💯" },
    
    // --- Prepositions (前置詞) & Conjunctions (接続詞) ---
    { english: "in", japanese: "〜の中に", emoji: "📥" },
    { english: "on", japanese: "〜の上に", emoji: "👆" },
    { english: "under", japanese: "〜の下に", emoji: "👇" },
    { english: "by", japanese: "〜のそばに", emoji: "🧍" },
    { english: "at", japanese: "〜で", emoji: "🎯" },
    { english: "to", japanese: "〜へ", emoji: "➡️" },
    { english: "from", japanese: "〜から", emoji: "⬅️" },
    { english: "with", japanese: "〜と一緒に", emoji: "🧑‍🤝‍🧑" },
    { english: "for", japanese: "〜のために", emoji: "🎁" },
    { english: "about", japanese: "〜について", emoji: "ℹ️" },
    { english: "before", japanese: "〜の前に", emoji: "⏪" },
    { english: "after", japanese: "〜の後に", emoji: "⏩" },
    { english: "and", japanese: "そして", emoji: "&" },
    { english: "but", japanese: "しかし", emoji: "↔️" },
    { english: "or", japanese: "または", emoji: "❓" },
    { english: "so", japanese: "だから", emoji: "➡️" },
    { english: "because", japanese: "なぜなら", emoji: "💬" },

    // --- Question Words (疑問詞) ---
    { english: "who", japanese: "だれが", emoji: "👤🤔" },
    { english: "what", japanese: "なにを", emoji: "💼🤔" },
    { english: "when", japanese: "いつ", emoji: "🕒🤔" },
    { english: "where", japanese: "どこで", emoji: "🚪🤔" },
    { english: "why", japanese: "なぜ", emoji: "🤔❓" },
    { english: "which", japanese: "どちらを", emoji: "🤔" },
    { english: "how", japanese: "どうやって", emoji: "🤔" },

    // --- Common Phrases (よく使う表現) ---
    { english: "Good morning.", japanese: "おはよう", emoji: "☀️🗣" },
    { english: "Thank you.", japanese: "ありがとう", emoji: "🙏🗣" },
    { english: "You're welcome.", japanese: "どういたしまして", emoji: "😊🗣" },
    { english: "I'm sorry.", japanese: "ごめんなさい", emoji: "😔🗣" },
    { english: "Excuse me.", japanese: "すみません", emoji: "🙋🗣" },
    { english: "Nice to meet you.", japanese: "はじめまして", emoji: "🤝🗣" },
    { english: "How are you?", japanese: "元気ですか？", emoji: "❓🗣" },
    { english: "I'm fine.", japanese: "元気です", emoji: "👍🗣" },
    { english: "Let's ...", japanese: "〜しましょう", emoji: "🙌🗣" },
    { english: "I can ...", japanese: "私は〜できます", emoji: "💪🗣" },
    { english: "I want to ...", japanese: "〜したいです", emoji: "🌟🗣" },
    { english: "I'm going to ...", japanese: "〜するつもりです", emoji: "🚀🗣" },
    { english: "What time is it?", japanese: "何時ですか？", emoji: "⏰❓" },
    { english: "It's ... o'clock.", japanese: "〜時です", emoji: "🕰️" },
    { english: "Where is ...?", japanese: "〜はどこですか？", emoji: "🗺️❓" },
    { english: "How much?", japanese: "いくらですか？", emoji: "💰" },
    { english: "What did you do?", japanese: "何をしましたか？", emoji: "❓" },
    { english: "I went to ...", japanese: "〜へ行きました", emoji: "➡️" },
    { english: "Of course.", japanese: "もちろん", emoji: "👌" },
    { english: "Me, too.", japanese: "私もです", emoji: "🙋‍♀️" },
    { english: "See you.", japanese: "またね", emoji: "👋" },
];
